---
- hosts: localhost
  gather_facts: no
  vars:
    description: Ensure DNS hostname resolution works before continuing
  tasks:
    - name: begin loop
      shell: host {{ lookup('env','HOSTNAME') }}
      register: result
      until: result.rc == 0
      retries: 200
      delay: 10