---
- hosts: localhost
  gather_facts: no
  vars:
    description: Ensure DNS hostname resolution works before continuing
  tasks:
    - name: Wait for DNS hostname resolution
      wait_for:
        port: 22
        host: '{{ item }}'
        connect_timeout: 10
        timeout: 2000
        state: started
      with_items: "{{ query('inventory_hostnames', 'all') }}"
      connection: local
