---
- hosts: localhost
  gather_facts: no
  tasks:
  - lineinfile:
      dest: /etc/ansible/hosts
      insertafter: '[new_nodes]'
      line: "$NODE openshift_node_labels=\"{'type': 'app', 'zone': 'default'}\" openshift_hostname=$NODE"
      regexp: '^$NODE '
      state: present
